

integration_tests:
  target: postgres

  outputs:
    postgres:
      type: postgres
      host: localhost
      user: shashankvashishtha
      password: ""               
      port: 5432
      dbname: dbt_snowplow
      schema: snplw_unified_int_tests
      threads: 4



    spark_iceberg:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      user: shashankvashishtha
      schema: snplw_unified_int_tests
      connect_retries: 5
      connect_timeout: 60
      threads: 1
      vars:
        snowplow__datalake_file_format: iceberg
